name: Check Invoice Ninja version

#on:
#  schedule:
#    - cron:  '*/10 * * * *'
on: workflow_dispatch

jobs:
  version-check:
    runs-on: ubuntu-latest
    steps:
      - name: Getting version of latest Docker tag
        id: jq
        uses: sergeysova/jq-action@v2
        with:
          cmd: |
            curl -L --fail "https://hub.docker.com/v2/repositories/michailkorenev/invoiceninja/tags/?page_size=1000" | jq '.results | .[] | .name' -r | sed 's/latest//' | sort --version-sort | tail -n 1

      - name: Version check
        id: check
        run: |
          UPDATE_NEEDED=0
          NINJA_CURRENT="$(wget -T 15 -qO- https://raw.githubusercontent.com/invoiceninja/invoiceninja/v5-stable/VERSION.txt)"
          NINJA_DOCKER=${{ steps.jq.outputs.value }}
          echo "NINJA_CURRENT: ${NINJA_CURRENT}"
          echo "NINJA_DOCKER: ${NINJA_DOCKER}"
              